# pnpm workspace configuration
# This file defines the workspace structure for pnpm

packages:
  # Root packages
  - "packages/*"
  - "apps/*"

  # Exclude specific directories
  - "!**/node_modules"
  - "!**/dist"
  - "!**/build"
  - "!**/out"
  - "!**/coverage"

  # Include specific subdirectories if needed
  # - 'packages/*/packages/*'
